### ISSUE TITLE
Add sign in component 

### ISSUE THREAD

**Issue by stygian-96** [Elevate-Lab/seroton-inn#13]
# Feature Request

Code sign in component according to below design

Desktop View
![SignIn (1)](https://user-images.githubusercontent.com/54054289/97167764-60751900-17ad-11eb-857e-1b1cb39554c2.png)

Mobile View
![Signin-mobile-view](https://user-images.githubusercontent.com/54054289/97167940-ab8f2c00-17ad-11eb-820d-b076cf8d63f6.png)

**Comment by Elemento24** [comment]
Hey @stygian-96, can you please provide the pic used as the background, and the colors involved. Without that, the design may not exactly look the same!

**Comment by stygian-96** [comment]
Hey @Elemento24 if you don't mind then can I work on this issue ?
I am sorry! Actually I forgot to claim.

**Comment by Elemento24** [comment]
Sure 😄😄
