### ISSUE TITLE
Add the Sass Architecture and the User Profile Page

### ISSUE THREAD

**Issue by Elemento24** [Elevate-Lab/seroton-inn#14]
# Feature Request

- I will add the Sass, 4 folder architecture.
- I will also add a Global Media Query Manager, with flexible rem for all the screen widths
- I will also add the User Profile Page.

**Comment by Elemento24** [comment]
Hey @Tlazypanda , I want to work on this, can you please assign this to me.
This is the Figma Design provided by Adarsh!

![User Profile](https://user-images.githubusercontent.com/58396433/97315921-37c55000-188f-11eb-9ddd-b5053e3a4946.jpg)

**Comment by stygian-96** [comment]
Color Shades:
#362073
#E3E1FF
#F3F3F3
#1E31DA
#34D226
#A293FF
#C2C2C2
#C2C7F0
#F2EFFF

![image](https://user-images.githubusercontent.com/54054289/97335138-7d8c1380-18a3-11eb-94de-dab38acd7bae.png)

**Comment by Elemento24** [comment]
Hey @Tlazypanda and @rush-tea, can you please have a look at these screenshots. I have made the first draft. Please tell me, if any further changes are required! Here is the live link
https://seroton-inn.netlify.app/profile

![Screenshot from 2020-10-28 13-24-30](https://user-images.githubusercontent.com/58396433/97407998-81f71180-1921-11eb-8d6f-838623becbc2.png)
![Screenshot from 2020-10-28 13-24-42](https://user-images.githubusercontent.com/58396433/97408004-83c0d500-1921-11eb-85c8-23c5d3189c03.png)
![Screenshot from 2020-10-28 13-24-53](https://user-images.githubusercontent.com/58396433/97408008-84f20200-1921-11eb-884d-d49b71f2aa34.png)
![Screenshot from 2020-10-28 13-25-04](https://user-images.githubusercontent.com/58396433/97408012-86232f00-1921-11eb-8815-a5f747c16b72.png)
![Screenshot from 2020-10-28 13-25-13](https://user-images.githubusercontent.com/58396433/97408015-87545c00-1921-11eb-98cc-c673cdfd7366.png)

**Comment by rush-tea** [comment]
hey @Elemento24 i think making the items in post container scrollable will be good...
