### ISSUE TITLE
Add Compose Page

### ISSUE THREAD

**Issue by 2802harsh** [Elevate-Lab/seroton-inn#15]
# Feature Request

### Describe your problem

Build the Compose page for the posts. It should include features such as text formatting, inserting pictures, emojis , word limit, etc

**Comment by 2802harsh** [comment]
Pls assign this issue to me and @sarthakm21

**Comment by IC1101Virgo** [comment]
ok ! Assigning to @2802harsh and @sarthakm21 😄

**Comment by IC1101Virgo** [comment]
Hey guys any updates? 🥇
