### ISSUE TITLE
Add Create Account component

### ISSUE THREAD

**Issue by garvitchittora** [Elevate-Lab/seroton-inn#19]
# Feature Request

### Describe your problem
Code up "Create Account" component according to design given below

## Desktop view

![Group 1](https://user-images.githubusercontent.com/54021348/97417818-1f584280-192e-11eb-8882-f62258fb03b8.png)

## Mobile view

![Signin-mobile-view (2)](https://user-images.githubusercontent.com/54021348/97417839-24b58d00-192e-11eb-891e-840c2fbc7337.png)

**Comment by garvitchittora** [comment]
pls assign this issue to me 😜.

**Comment by IC1101Virgo** [comment]
Hey @garvitchittora can we work together on this issue?

**Comment by IC1101Virgo** [comment]
Assigned #19 to @garvitchittora
