### ISSUE TITLE
Improve home page

### ISSUE THREAD

**Issue by stygian-96** [Elevate-Lab/seroton-inn#30]
### Changes: 

-> Remove sidebar from home page
-> Add `box-shadow: 0px 0px 50px -18px rgba(0, 0, 0, 0.25);` to each containers
-> Change color of compose button to`#C5C3FF`
-> Max width of the main container should be `1280px`
-> When windows width is less than `1280px` give it a margin of 12px
-> Hide notifications container when windows width is less than 900px

### Img

![Home-desktop](https://user-images.githubusercontent.com/54054289/102708914-03d53c80-42cc-11eb-94f6-54afcbb5341e.png)

![Home-mobile](https://user-images.githubusercontent.com/54054289/102708907-f3bd5d00-42cb-11eb-92d2-868be2ec870f.png)

**Comment by rush-tea** [comment]
@stygian-96  can i do this?

**Comment by stygian-96** [comment]
Yes! Go ahead 👍
