### ISSUE TITLE
Improve profile page

### ISSUE THREAD

**Issue by stygian-96** [Elevate-Lab/seroton-inn#31]
### Changes: 

-> Remove sidebar from home page
-> Add `box-shadow: 0px 0px 50px -18px rgba(0, 0, 0, 0.25);` to each containers
-> Change color of follow button and not selected tab to`#C5C3FF`
-> Max width of the main container should be `1280px`
-> When windows width is less than `1280px` give it a margin of 12px

### Img

![Profile (1)](https://user-images.githubusercontent.com/54054289/102709014-aa214200-42cc-11eb-910c-839205265aac.png)

![Profile-mobile](https://user-images.githubusercontent.com/54054289/102709020-b86f5e00-42cc-11eb-9e39-f06fce6d9a84.png)

**Comment by rush-tea** [comment]
@Tlazypanda @uglyprincess i would like to work on this :))
