### ISSUE TITLE
Making User Interface for edit Profile page

### ISSUE THREAD

**Issue by rush-tea** [Elevate-Lab/seroton-inn#40]
# Feature Request

### Describe your problem

Recently there is a simple UI for edit profile page which is just for testing for backend REST Api endpoints, there is need to improve its UI. We have the designs for edit profile page which we can get [here](https://www.figma.com/file/Yf4BwLjrU92BF5Fx4Qwo0c/Seroton-Inn?node-id=328%3A142).

**Comment by rush-tea** [comment]
@stygian-96 Can i work on this?

**Comment by stygian-96** [comment]
Yes sure!
