### ISSUE TITLE
Add Figma Design

### ISSUE THREAD

**Issue by IC1101Virgo** [Elevate-Lab/seroton-inn#5]
Figma design for the platform needed so that we have a basic idea of what the platform looks like.
An idea of color schemes could be good like whether we want to have yellow 🟡  as the main theme or maybe green 🟢 it can be any color 🌈 .
Also design for other pages ! 😀

**Comment by Tlazypanda** [comment]
Hey @hardikbajaj @rush-tea @sarthakm21 @garvitchittora @stygian-96 since all of you volunteered for frontend work, get started with opening the issues for the project structure and page designs soon :v:

**Comment by deepakDOTexe** [comment]
You can add a link to the figma file in the readme file and make a PR to close this issue.

**Comment by IC1101Virgo** [comment]
What's the activity on this issue? Are designs still needed?
