### ISSUE TITLE
Add basic react project structure

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/seroton-inn#7]
# Feature Request

### Describe your problem
Add basic react project structure.

**Comment by Elemento24** [comment]
Hey @Tlazypanda, should I use create-react-app or should I configure the webpack, and then create the basic project structure.

**Comment by Elemento24** [comment]
Hey @Tlazypanda, I have added the basic react app structure, using create-react-app. Should I also add the edit the README.md to include the steps as to how to start the app, or will you make a new Issue for that?
